// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Ubiquitous.AutoDevOps.Crds.CertManager.Certmanager.V1.Outputs
{

    [OutputType]
    public sealed class CertificateSpecKeystores
    {
        /// <summary>
        /// JKS configures options for storing a JKS keystore in the `spec.secretName` Secret resource.
        /// </summary>
        public readonly CertificateSpecKeystoresJks Jks;
        /// <summary>
        /// PKCS12 configures options for storing a PKCS12 keystore in the `spec.secretName` Secret resource.
        /// </summary>
        public readonly CertificateSpecKeystoresPkcs12 Pkcs12;

        [OutputConstructor]
        private CertificateSpecKeystores(
            CertificateSpecKeystoresJks jks,

            CertificateSpecKeystoresPkcs12 pkcs12)
        {
            Jks = jks;
            Pkcs12 = pkcs12;
        }
    }
}
