// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Ubiquitous.AutoDevOps.Crds.CertManager.Certmanager.V1.Outputs
{

    [OutputType]
    public sealed class IssuerStatusAcme
    {
        /// <summary>
        /// LastRegisteredEmail is the email associated with the latest registered ACME account, in order to track changes made to registered account associated with the  Issuer
        /// </summary>
        public readonly string LastRegisteredEmail;
        /// <summary>
        /// URI is the unique account identifier, which can also be used to retrieve account details from the CA
        /// </summary>
        public readonly string Uri;

        [OutputConstructor]
        private IssuerStatusAcme(
            string lastRegisteredEmail,

            string uri)
        {
            LastRegisteredEmail = lastRegisteredEmail;
            Uri = uri;
        }
    }
}
