// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Ubiquitous.AutoDevOps.Crds.CertManager.Certmanager.V1.Outputs
{

    [OutputType]
    public sealed class IssuerSpecAcmeSolversDns01AzureDNS
    {
        /// <summary>
        /// if both this and ClientSecret are left unset MSI will be used
        /// </summary>
        public readonly string ClientID;
        /// <summary>
        /// if both this and ClientID are left unset MSI will be used
        /// </summary>
        public readonly IssuerSpecAcmeSolversDns01AzureDNSClientSecretSecretRef ClientSecretSecretRef;
        public readonly string Environment;
        public readonly string HostedZoneName;
        public readonly string ResourceGroupName;
        public readonly string SubscriptionID;
        /// <summary>
        /// when specifying ClientID and ClientSecret then this field is also needed
        /// </summary>
        public readonly string TenantID;

        [OutputConstructor]
        private IssuerSpecAcmeSolversDns01AzureDNS(
            string clientID,

            IssuerSpecAcmeSolversDns01AzureDNSClientSecretSecretRef clientSecretSecretRef,

            string environment,

            string hostedZoneName,

            string resourceGroupName,

            string subscriptionID,

            string tenantID)
        {
            ClientID = clientID;
            ClientSecretSecretRef = clientSecretSecretRef;
            Environment = environment;
            HostedZoneName = hostedZoneName;
            ResourceGroupName = resourceGroupName;
            SubscriptionID = subscriptionID;
            TenantID = tenantID;
        }
    }
}
