// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Ubiquitous.AutoDevOps.Crds.CertManager.Certmanager.V1.Outputs
{

    [OutputType]
    public sealed class IssuerSpecAcmeSolversHttp01IngressPodTemplate
    {
        /// <summary>
        /// ObjectMeta overrides for the pod used to solve HTTP01 challenges. Only the 'labels' and 'annotations' fields may be set. If labels or annotations overlap with in-built values, the values here will override the in-built values.
        /// </summary>
        public readonly IssuerSpecAcmeSolversHttp01IngressPodTemplateMetadata Metadata;
        /// <summary>
        /// PodSpec defines overrides for the HTTP01 challenge solver pod. Only the 'priorityClassName', 'nodeSelector', 'affinity', 'serviceAccountName' and 'tolerations' fields are supported currently. All other fields will be ignored.
        /// </summary>
        public readonly IssuerSpecAcmeSolversHttp01IngressPodTemplateSpec Spec;

        [OutputConstructor]
        private IssuerSpecAcmeSolversHttp01IngressPodTemplate(
            IssuerSpecAcmeSolversHttp01IngressPodTemplateMetadata metadata,

            IssuerSpecAcmeSolversHttp01IngressPodTemplateSpec spec)
        {
            Metadata = metadata;
            Spec = spec;
        }
    }
}
