// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Monitoring.V1
{

    /// <summary>
    /// Specification of desired Pod selection for target discovery by Prometheus.
    /// </summary>
    public class PodMonitorSpecArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The label to use to retrieve the job name from.
        /// </summary>
        [Input("jobLabel")]
        public Input<string>? JobLabel { get; set; }

        /// <summary>
        /// Selector to select which namespaces the Endpoints objects are discovered from.
        /// </summary>
        [Input("namespaceSelector")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.PodMonitorSpecNamespaceSelectorArgs>? NamespaceSelector { get; set; }

        [Input("podMetricsEndpoints", required: true)]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.PodMonitorSpecPodMetricsEndpointsArgs>? _podMetricsEndpoints;

        /// <summary>
        /// A list of endpoints allowed as part of this PodMonitor.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.PodMonitorSpecPodMetricsEndpointsArgs> PodMetricsEndpoints
        {
            get => _podMetricsEndpoints ?? (_podMetricsEndpoints = new InputList<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.PodMonitorSpecPodMetricsEndpointsArgs>());
            set => _podMetricsEndpoints = value;
        }

        [Input("podTargetLabels")]
        private InputList<string>? _podTargetLabels;

        /// <summary>
        /// PodTargetLabels transfers labels on the Kubernetes Pod onto the target.
        /// </summary>
        public InputList<string> PodTargetLabels
        {
            get => _podTargetLabels ?? (_podTargetLabels = new InputList<string>());
            set => _podTargetLabels = value;
        }

        /// <summary>
        /// SampleLimit defines per-scrape limit on number of scraped samples that will be accepted.
        /// </summary>
        [Input("sampleLimit")]
        public Input<int>? SampleLimit { get; set; }

        /// <summary>
        /// Selector to select Pod objects.
        /// </summary>
        [Input("selector", required: true)]
        public Input<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.PodMonitorSpecSelectorArgs> Selector { get; set; } = null!;

        /// <summary>
        /// TargetLimit defines a limit on the number of scraped targets that will be accepted.
        /// </summary>
        [Input("targetLimit")]
        public Input<int>? TargetLimit { get; set; }

        public PodMonitorSpecArgs()
        {
        }
    }
}
