// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Ubiquitous.AutoDevOps.Crds.CertManager.Certmanager.V1Beta1.Inputs
{

    /// <summary>
    /// Status of the CertificateRequest. This is set and managed automatically.
    /// </summary>
    public class CertificateRequestStatusArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The PEM encoded x509 certificate of the signer, also known as the CA (Certificate Authority). This is set on a best-effort basis by different issuers. If not set, the CA is assumed to be unknown/not available.
        /// </summary>
        [Input("ca")]
        public Input<string>? Ca { get; set; }

        /// <summary>
        /// The PEM encoded x509 certificate resulting from the certificate signing request. If not set, the CertificateRequest has either not been completed or has failed. More information on failure can be found by checking the `conditions` field.
        /// </summary>
        [Input("certificate")]
        public Input<string>? Certificate { get; set; }

        [Input("conditions")]
        private InputList<CertificateRequestStatusConditionsArgs>? _conditions;

        /// <summary>
        /// List of status conditions to indicate the status of a CertificateRequest. Known condition types are `Ready` and `InvalidRequest`.
        /// </summary>
        public InputList<CertificateRequestStatusConditionsArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<CertificateRequestStatusConditionsArgs>());
            set => _conditions = value;
        }

        /// <summary>
        /// FailureTime stores the time that this CertificateRequest failed. This is used to influence garbage collection and back-off.
        /// </summary>
        [Input("failureTime")]
        public Input<string>? FailureTime { get; set; }

        public CertificateRequestStatusArgs()
        {
        }
    }
}
