// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Ubiquitous.AutoDevOps.Crds.CertManager.Certmanager.V1Beta1.Inputs
{

    /// <summary>
    /// Status of the ClusterIssuer. This is set and managed automatically.
    /// </summary>
    public class ClusterIssuerStatusArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// ACME specific status options. This field should only be set if the Issuer is configured to use an ACME server to issue certificates.
        /// </summary>
        [Input("acme")]
        public Input<ClusterIssuerStatusAcmeArgs>? Acme { get; set; }

        [Input("conditions")]
        private InputList<ClusterIssuerStatusConditionsArgs>? _conditions;

        /// <summary>
        /// List of status conditions to indicate the status of a CertificateRequest. Known condition types are `Ready`.
        /// </summary>
        public InputList<ClusterIssuerStatusConditionsArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<ClusterIssuerStatusConditionsArgs>());
            set => _conditions = value;
        }

        public ClusterIssuerStatusArgs()
        {
        }
    }
}
