// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Ubiquitous.AutoDevOps.Crds.CertManager.Certmanager.V1.Inputs
{

    /// <summary>
    /// Status of the Certificate. This is set and managed automatically.
    /// </summary>
    public class CertificateStatusArgs : Pulumi.ResourceArgs
    {
        [Input("conditions")]
        private InputList<CertificateStatusConditionsArgs>? _conditions;

        /// <summary>
        /// List of status conditions to indicate the status of certificates. Known condition types are `Ready` and `Issuing`.
        /// </summary>
        public InputList<CertificateStatusConditionsArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<CertificateStatusConditionsArgs>());
            set => _conditions = value;
        }

        /// <summary>
        /// LastFailureTime is the time as recorded by the Certificate controller of the most recent failure to complete a CertificateRequest for this Certificate resource. If set, cert-manager will not re-request another Certificate until 1 hour has elapsed from this time.
        /// </summary>
        [Input("lastFailureTime")]
        public Input<string>? LastFailureTime { get; set; }

        /// <summary>
        /// The name of the Secret resource containing the private key to be used for the next certificate iteration. The keymanager controller will automatically set this field if the `Issuing` condition is set to `True`. It will automatically unset this field when the Issuing condition is not set or False.
        /// </summary>
        [Input("nextPrivateKeySecretName")]
        public Input<string>? NextPrivateKeySecretName { get; set; }

        /// <summary>
        /// The expiration time of the certificate stored in the secret named by this resource in `spec.secretName`.
        /// </summary>
        [Input("notAfter")]
        public Input<string>? NotAfter { get; set; }

        /// <summary>
        /// The time after which the certificate stored in the secret named by this resource in spec.secretName is valid.
        /// </summary>
        [Input("notBefore")]
        public Input<string>? NotBefore { get; set; }

        /// <summary>
        /// RenewalTime is the time at which the certificate will be next renewed. If not set, no upcoming renewal is scheduled.
        /// </summary>
        [Input("renewalTime")]
        public Input<string>? RenewalTime { get; set; }

        /// <summary>
        /// The current 'revision' of the certificate as issued. 
        ///  When a CertificateRequest resource is created, it will have the `cert-manager.io/certificate-revision` set to one greater than the current value of this field. 
        ///  Upon issuance, this field will be set to the value of the annotation on the CertificateRequest resource used to issue the certificate. 
        ///  Persisting the value on the CertificateRequest resource allows the certificates controller to know whether a request is part of an old issuance or if it is part of the ongoing revision's issuance by checking if the revision value in the annotation is greater than this field.
        /// </summary>
        [Input("revision")]
        public Input<int>? Revision { get; set; }

        public CertificateStatusArgs()
        {
        }
    }
}
