// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Ubiquitous.AutoDevOps.Crds.CertManager.Certmanager.V1.Inputs
{

    /// <summary>
    /// Keystores configures additional keystore output formats stored in the `secretName` Secret resource.
    /// </summary>
    public class CertificateSpecKeystoresArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// JKS configures options for storing a JKS keystore in the `spec.secretName` Secret resource.
        /// </summary>
        [Input("jks")]
        public Input<CertificateSpecKeystoresJksArgs>? Jks { get; set; }

        /// <summary>
        /// PKCS12 configures options for storing a PKCS12 keystore in the `spec.secretName` Secret resource.
        /// </summary>
        [Input("pkcs12")]
        public Input<CertificateSpecKeystoresPkcs12Args>? Pkcs12 { get; set; }

        public CertificateSpecKeystoresArgs()
        {
        }
    }
}
