// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Ubiquitous.AutoDevOps.Crds.CertManager.Certmanager.V1.Inputs
{

    /// <summary>
    /// Use the DigitalOcean DNS API to manage DNS01 challenge records.
    /// </summary>
    public class ClusterIssuerSpecAcmeSolversDns01DigitaloceanArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// A reference to a specific 'key' within a Secret resource. In some instances, `key` is a required field.
        /// </summary>
        [Input("tokenSecretRef", required: true)]
        public Input<ClusterIssuerSpecAcmeSolversDns01DigitaloceanTokenSecretRefArgs> TokenSecretRef { get; set; } = null!;

        public ClusterIssuerSpecAcmeSolversDns01DigitaloceanArgs()
        {
        }
    }
}
