// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Ubiquitous.AutoDevOps.Crds.CertManager.Certmanager.V1.Inputs
{

    /// <summary>
    /// The ingress based HTTP01 challenge solver will solve challenges by creating or modifying Ingress resources in order to route requests for '/.well-known/acme-challenge/XYZ' to 'challenge solver' pods that are provisioned by cert-manager for each Challenge to be completed.
    /// </summary>
    public class IssuerSpecAcmeSolversHttp01IngressArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ingress class to use when creating Ingress resources to solve ACME challenges that use this challenge solver. Only one of 'class' or 'name' may be specified.
        /// </summary>
        [Input("class")]
        public Input<string>? Class { get; set; }

        /// <summary>
        /// Optional ingress template used to configure the ACME challenge solver ingress used for HTTP01 challenges
        /// </summary>
        [Input("ingressTemplate")]
        public Input<IssuerSpecAcmeSolversHttp01IngressIngressTemplateArgs>? IngressTemplate { get; set; }

        /// <summary>
        /// The name of the ingress resource that should have ACME challenge solving routes inserted into it in order to solve HTTP01 challenges. This is typically used in conjunction with ingress controllers like ingress-gce, which maintains a 1:1 mapping between external IPs and ingress resources.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Optional pod template used to configure the ACME challenge solver pods used for HTTP01 challenges
        /// </summary>
        [Input("podTemplate")]
        public Input<IssuerSpecAcmeSolversHttp01IngressPodTemplateArgs>? PodTemplate { get; set; }

        /// <summary>
        /// Optional service type for Kubernetes solver service
        /// </summary>
        [Input("serviceType")]
        public Input<string>? ServiceType { get; set; }

        public IssuerSpecAcmeSolversHttp01IngressArgs()
        {
        }
    }
}
