// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Monitoring.V1
{

    [OutputType]
    public sealed class PodMonitorSpecPodMetricsEndpointsTlsConfig
    {
        /// <summary>
        /// Struct containing the CA cert to use for the targets.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Monitoring.V1.PodMonitorSpecPodMetricsEndpointsTlsConfigCa Ca;
        /// <summary>
        /// Struct containing the client cert file for the targets.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Monitoring.V1.PodMonitorSpecPodMetricsEndpointsTlsConfigCert Cert;
        /// <summary>
        /// Disable target certificate validation.
        /// </summary>
        public readonly bool InsecureSkipVerify;
        /// <summary>
        /// Secret containing the client key file for the targets.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Monitoring.V1.PodMonitorSpecPodMetricsEndpointsTlsConfigKeySecret KeySecret;
        /// <summary>
        /// Used to verify the hostname for the targets.
        /// </summary>
        public readonly string ServerName;

        [OutputConstructor]
        private PodMonitorSpecPodMetricsEndpointsTlsConfig(
            Pulumi.Kubernetes.Types.Outputs.Monitoring.V1.PodMonitorSpecPodMetricsEndpointsTlsConfigCa ca,

            Pulumi.Kubernetes.Types.Outputs.Monitoring.V1.PodMonitorSpecPodMetricsEndpointsTlsConfigCert cert,

            bool insecureSkipVerify,

            Pulumi.Kubernetes.Types.Outputs.Monitoring.V1.PodMonitorSpecPodMetricsEndpointsTlsConfigKeySecret keySecret,

            string serverName)
        {
            Ca = ca;
            Cert = cert;
            InsecureSkipVerify = insecureSkipVerify;
            KeySecret = keySecret;
            ServerName = serverName;
        }
    }
}
