// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Monitoring.V1
{

    /// <summary>
    /// TLS configuration to use when scraping the endpoint.
    /// </summary>
    public class PodMonitorSpecPodMetricsEndpointsTlsConfigArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Struct containing the CA cert to use for the targets.
        /// </summary>
        [Input("ca")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.PodMonitorSpecPodMetricsEndpointsTlsConfigCaArgs>? Ca { get; set; }

        /// <summary>
        /// Struct containing the client cert file for the targets.
        /// </summary>
        [Input("cert")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.PodMonitorSpecPodMetricsEndpointsTlsConfigCertArgs>? Cert { get; set; }

        /// <summary>
        /// Disable target certificate validation.
        /// </summary>
        [Input("insecureSkipVerify")]
        public Input<bool>? InsecureSkipVerify { get; set; }

        /// <summary>
        /// Secret containing the client key file for the targets.
        /// </summary>
        [Input("keySecret")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.PodMonitorSpecPodMetricsEndpointsTlsConfigKeySecretArgs>? KeySecret { get; set; }

        /// <summary>
        /// Used to verify the hostname for the targets.
        /// </summary>
        [Input("serverName")]
        public Input<string>? ServerName { get; set; }

        public PodMonitorSpecPodMetricsEndpointsTlsConfigArgs()
        {
        }
    }
}
