// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Monitoring.V1
{

    /// <summary>
    /// Specification of desired Service selection for target discovery by Prometheus.
    /// </summary>
    public class ServiceMonitorSpecArgs : Pulumi.ResourceArgs
    {
        [Input("endpoints", required: true)]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.ServiceMonitorSpecEndpointsArgs>? _endpoints;

        /// <summary>
        /// A list of endpoints allowed as part of this ServiceMonitor.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.ServiceMonitorSpecEndpointsArgs> Endpoints
        {
            get => _endpoints ?? (_endpoints = new InputList<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.ServiceMonitorSpecEndpointsArgs>());
            set => _endpoints = value;
        }

        /// <summary>
        /// The label to use to retrieve the job name from.
        /// </summary>
        [Input("jobLabel")]
        public Input<string>? JobLabel { get; set; }

        /// <summary>
        /// Selector to select which namespaces the Endpoints objects are discovered from.
        /// </summary>
        [Input("namespaceSelector")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.ServiceMonitorSpecNamespaceSelectorArgs>? NamespaceSelector { get; set; }

        [Input("podTargetLabels")]
        private InputList<string>? _podTargetLabels;

        /// <summary>
        /// PodTargetLabels transfers labels on the Kubernetes Pod onto the target.
        /// </summary>
        public InputList<string> PodTargetLabels
        {
            get => _podTargetLabels ?? (_podTargetLabels = new InputList<string>());
            set => _podTargetLabels = value;
        }

        /// <summary>
        /// SampleLimit defines per-scrape limit on number of scraped samples that will be accepted.
        /// </summary>
        [Input("sampleLimit")]
        public Input<int>? SampleLimit { get; set; }

        /// <summary>
        /// Selector to select Endpoints objects.
        /// </summary>
        [Input("selector", required: true)]
        public Input<Pulumi.Kubernetes.Types.Inputs.Monitoring.V1.ServiceMonitorSpecSelectorArgs> Selector { get; set; } = null!;

        [Input("targetLabels")]
        private InputList<string>? _targetLabels;

        /// <summary>
        /// TargetLabels transfers labels on the Kubernetes Service onto the target.
        /// </summary>
        public InputList<string> TargetLabels
        {
            get => _targetLabels ?? (_targetLabels = new InputList<string>());
            set => _targetLabels = value;
        }

        /// <summary>
        /// TargetLimit defines a limit on the number of scraped targets that will be accepted.
        /// </summary>
        [Input("targetLimit")]
        public Input<int>? TargetLimit { get; set; }

        public ServiceMonitorSpecArgs()
        {
        }
    }
}
