// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;
using Pulumi;
using Ubiquitous.AutoDevOps.Crds.CertManager.Certmanager.V1.Inputs;
using Ubiquitous.AutoDevOps.Crds.CertManager.Certmanager.V1.Outputs;

namespace Ubiquitous.AutoDevOps.Crds.CertManager.Certmanager.V1 {
    /// <summary>
    /// A CertificateRequest is used to request a signed certificate from one of the configured issuers.
    ///  All fields within the CertificateRequest's `spec` are immutable after creation. A CertificateRequest will either succeed or fail, as denoted by its `status.state` field.
    ///  A CertificateRequest is a one-shot resource, meaning it represents a single point in time request for a certificate and cannot be re-used.
    /// </summary>
    public partial class CertificateRequest : KubernetesResource {
        [Output("apiVersion")] public Output<string> ApiVersion { get; private set; } = null!;

        [Output("kind")] public Output<string> Kind { get; private set; } = null!;

        [Output("metadata")]
        public Output<Pulumi.Kubernetes.Types.Outputs.Meta.V1.ObjectMeta> Metadata { get; private set; } = null!;

        /// <summary>
        /// Desired state of the CertificateRequest resource.
        /// </summary>
        [Output("spec")]
        public Output<CertificateRequestSpec> Spec { get; private set; } = null!;

        /// <summary>
        /// Status of the CertificateRequest. This is set and managed automatically.
        /// </summary>
        [Output("status")]
        public Output<CertificateRequestStatus> Status { get; private set; } = null!;

        /// <summary>
        /// Create a CertificateRequest resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public CertificateRequest(
            string name, CertificateRequestArgs? args = null, CustomResourceOptions? options = null
        )
            : base(
                "kubernetes:cert-manager.io/v1:CertificateRequest",
                name,
                MakeArgs(args),
                MakeResourceOptions(options, "")
            ) { }

        internal CertificateRequest(
            string name, ImmutableDictionary<string, object?> dictionary, CustomResourceOptions? options = null
        )
            : base(
                "kubernetes:cert-manager.io/v1:CertificateRequest",
                name,
                new DictionaryResourceArgs(dictionary),
                MakeResourceOptions(options, "")
            ) { }

        CertificateRequest(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("kubernetes:cert-manager.io/v1:CertificateRequest", name, null, MakeResourceOptions(options, id)) { }

        static CertificateRequestArgs? MakeArgs(CertificateRequestArgs? args) {
            args            ??= new CertificateRequestArgs();
            args.ApiVersion =   "cert-manager.io/v1";
            args.Kind       =   "CertificateRequest";
            return args;
        }

        static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id) {
            var defaultOptions = new CustomResourceOptions {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }

        /// <summary>
        /// Get an existing CertificateRequest resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static CertificateRequest Get(string name, Input<string> id, CustomResourceOptions? options = null) {
            return new(name, id, options);
        }
    }

    public class CertificateRequestArgs : ResourceArgs {
        [Input("apiVersion")] public Input<string>? ApiVersion { get; set; }

        [Input("kind")] public Input<string>? Kind { get; set; }

        [Input("metadata")] public Input<Pulumi.Kubernetes.Types.Inputs.Meta.V1.ObjectMetaArgs>? Metadata { get; set; }

        /// <summary>
        /// Desired state of the CertificateRequest resource.
        /// </summary>
        [Input("spec")]
        public Input<CertificateRequestSpecArgs>? Spec { get; set; }

        /// <summary>
        /// Status of the CertificateRequest. This is set and managed automatically.
        /// </summary>
        [Input("status")]
        public Input<CertificateRequestStatusArgs>? Status { get; set; }

        public CertificateRequestArgs() { }
    }
}