// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Monitoring.V1
{

    [OutputType]
    public sealed class PodMonitorSpecPodMetricsEndpointsBasicAuth
    {
        /// <summary>
        /// The secret in the service monitor namespace that contains the password for authentication.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Monitoring.V1.PodMonitorSpecPodMetricsEndpointsBasicAuthPassword Password;
        /// <summary>
        /// The secret in the service monitor namespace that contains the username for authentication.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Monitoring.V1.PodMonitorSpecPodMetricsEndpointsBasicAuthUsername Username;

        [OutputConstructor]
        private PodMonitorSpecPodMetricsEndpointsBasicAuth(
            Pulumi.Kubernetes.Types.Outputs.Monitoring.V1.PodMonitorSpecPodMetricsEndpointsBasicAuthPassword password,

            Pulumi.Kubernetes.Types.Outputs.Monitoring.V1.PodMonitorSpecPodMetricsEndpointsBasicAuthUsername username)
        {
            Password = password;
            Username = username;
        }
    }
}
