// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Ubiquitous.AutoDevOps.Crds.Prometheus.Monitoring.V1.Outputs
{

    [OutputType]
    public sealed class PodMonitorSpecPodMetricsEndpointsBasicAuth
    {
        /// <summary>
        /// The secret in the service monitor namespace that contains the password for authentication.
        /// </summary>
        public readonly PodMonitorSpecPodMetricsEndpointsBasicAuthPassword Password;
        /// <summary>
        /// The secret in the service monitor namespace that contains the username for authentication.
        /// </summary>
        public readonly PodMonitorSpecPodMetricsEndpointsBasicAuthUsername Username;

        [OutputConstructor]
        private PodMonitorSpecPodMetricsEndpointsBasicAuth(
            PodMonitorSpecPodMetricsEndpointsBasicAuthPassword password,

            PodMonitorSpecPodMetricsEndpointsBasicAuthUsername username)
        {
            Password = password;
            Username = username;
        }
    }
}
