// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Ubiquitous.AutoDevOps.Crds.Prometheus.Monitoring.V1.Outputs
{

    [OutputType]
    public sealed class PodMonitorSpecPodMetricsEndpointsTlsConfig
    {
        /// <summary>
        /// Struct containing the CA cert to use for the targets.
        /// </summary>
        public readonly PodMonitorSpecPodMetricsEndpointsTlsConfigCa Ca;
        /// <summary>
        /// Struct containing the client cert file for the targets.
        /// </summary>
        public readonly PodMonitorSpecPodMetricsEndpointsTlsConfigCert Cert;
        /// <summary>
        /// Disable target certificate validation.
        /// </summary>
        public readonly bool InsecureSkipVerify;
        /// <summary>
        /// Secret containing the client key file for the targets.
        /// </summary>
        public readonly PodMonitorSpecPodMetricsEndpointsTlsConfigKeySecret KeySecret;
        /// <summary>
        /// Used to verify the hostname for the targets.
        /// </summary>
        public readonly string ServerName;

        [OutputConstructor]
        private PodMonitorSpecPodMetricsEndpointsTlsConfig(
            PodMonitorSpecPodMetricsEndpointsTlsConfigCa ca,

            PodMonitorSpecPodMetricsEndpointsTlsConfigCert cert,

            bool insecureSkipVerify,

            PodMonitorSpecPodMetricsEndpointsTlsConfigKeySecret keySecret,

            string serverName)
        {
            Ca = ca;
            Cert = cert;
            InsecureSkipVerify = insecureSkipVerify;
            KeySecret = keySecret;
            ServerName = serverName;
        }
    }
}
