// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Ubiquitous.AutoDevOps.Crds.Prometheus.Monitoring.V1.Outputs
{

    [OutputType]
    public sealed class PodMonitorSpecPodMetricsEndpointsTlsConfigCert
    {
        /// <summary>
        /// ConfigMap containing data to use for the targets.
        /// </summary>
        public readonly PodMonitorSpecPodMetricsEndpointsTlsConfigCertConfigMap ConfigMap;
        /// <summary>
        /// Secret containing data to use for the targets.
        /// </summary>
        public readonly PodMonitorSpecPodMetricsEndpointsTlsConfigCertSecret Secret;

        [OutputConstructor]
        private PodMonitorSpecPodMetricsEndpointsTlsConfigCert(
            PodMonitorSpecPodMetricsEndpointsTlsConfigCertConfigMap configMap,

            PodMonitorSpecPodMetricsEndpointsTlsConfigCertSecret secret)
        {
            ConfigMap = configMap;
            Secret = secret;
        }
    }
}
