// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Ubiquitous.AutoDevOps.Crds.Prometheus.Monitoring.V1.Outputs
{

    [OutputType]
    public sealed class ServiceMonitorSpecEndpointsTlsConfig
    {
        /// <summary>
        /// Struct containing the CA cert to use for the targets.
        /// </summary>
        public readonly ServiceMonitorSpecEndpointsTlsConfigCa Ca;
        /// <summary>
        /// Path to the CA cert in the Prometheus container to use for the targets.
        /// </summary>
        public readonly string CaFile;
        /// <summary>
        /// Struct containing the client cert file for the targets.
        /// </summary>
        public readonly ServiceMonitorSpecEndpointsTlsConfigCert Cert;
        /// <summary>
        /// Path to the client cert file in the Prometheus container for the targets.
        /// </summary>
        public readonly string CertFile;
        /// <summary>
        /// Disable target certificate validation.
        /// </summary>
        public readonly bool InsecureSkipVerify;
        /// <summary>
        /// Path to the client key file in the Prometheus container for the targets.
        /// </summary>
        public readonly string KeyFile;
        /// <summary>
        /// Secret containing the client key file for the targets.
        /// </summary>
        public readonly ServiceMonitorSpecEndpointsTlsConfigKeySecret KeySecret;
        /// <summary>
        /// Used to verify the hostname for the targets.
        /// </summary>
        public readonly string ServerName;

        [OutputConstructor]
        private ServiceMonitorSpecEndpointsTlsConfig(
            ServiceMonitorSpecEndpointsTlsConfigCa ca,

            string caFile,

            ServiceMonitorSpecEndpointsTlsConfigCert cert,

            string certFile,

            bool insecureSkipVerify,

            string keyFile,

            ServiceMonitorSpecEndpointsTlsConfigKeySecret keySecret,

            string serverName)
        {
            Ca = ca;
            CaFile = caFile;
            Cert = cert;
            CertFile = certFile;
            InsecureSkipVerify = insecureSkipVerify;
            KeyFile = keyFile;
            KeySecret = keySecret;
            ServerName = serverName;
        }
    }
}
