// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Ubiquitous.AutoDevOps.Crds.Prometheus.Monitoring.V1.Outputs
{

    [OutputType]
    public sealed class ServiceMonitorSpecEndpointsTargetPort
    {
        [OutputConstructor]
        private ServiceMonitorSpecEndpointsTargetPort()
        {
        }
    }
}
