// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Ubiquitous.AutoDevOps.Crds.Prometheus.Monitoring.V1.Outputs
{

    [OutputType]
    public sealed class ServiceMonitorSpecEndpointsTlsConfigCert
    {
        /// <summary>
        /// ConfigMap containing data to use for the targets.
        /// </summary>
        public readonly ServiceMonitorSpecEndpointsTlsConfigCertConfigMap ConfigMap;
        /// <summary>
        /// Secret containing data to use for the targets.
        /// </summary>
        public readonly ServiceMonitorSpecEndpointsTlsConfigCertSecret Secret;

        [OutputConstructor]
        private ServiceMonitorSpecEndpointsTlsConfigCert(
            ServiceMonitorSpecEndpointsTlsConfigCertConfigMap configMap,

            ServiceMonitorSpecEndpointsTlsConfigCertSecret secret)
        {
            ConfigMap = configMap;
            Secret = secret;
        }
    }
}
