// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;
using Pulumi;

namespace Ubiquitous.AutoDevOps.Crds.CertManager.Certmanager.V1Beta1.Outputs
{

    [OutputType]
    public sealed class ClusterIssuerStatus
    {
        /// <summary>
        /// ACME specific status options. This field should only be set if the Issuer is configured to use an ACME server to issue certificates.
        /// </summary>
        public readonly ClusterIssuerStatusAcme Acme;
        /// <summary>
        /// List of status conditions to indicate the status of a CertificateRequest. Known condition types are `Ready`.
        /// </summary>
        public readonly ImmutableArray<ClusterIssuerStatusConditions> Conditions;

        [OutputConstructor]
        private ClusterIssuerStatus(
            ClusterIssuerStatusAcme acme,

            ImmutableArray<ClusterIssuerStatusConditions> conditions)
        {
            Acme = acme;
            Conditions = conditions;
        }
    }
}
