// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Ubiquitous.AutoDevOps.Crds.CertManager.Certmanager.V1Beta1.Outputs
{

    [OutputType]
    public sealed class ClusterIssuerSpecVaultAuthAppRole
    {
        /// <summary>
        /// Path where the App Role authentication backend is mounted in Vault, e.g: "approle"
        /// </summary>
        public readonly string Path;
        /// <summary>
        /// RoleID configured in the App Role authentication backend when setting up the authentication backend in Vault.
        /// </summary>
        public readonly string RoleId;
        /// <summary>
        /// Reference to a key in a Secret that contains the App Role secret used to authenticate with Vault. The `key` field must be specified and denotes which entry within the Secret resource is used as the app role secret.
        /// </summary>
        public readonly ClusterIssuerSpecVaultAuthAppRoleSecretRef SecretRef;

        [OutputConstructor]
        private ClusterIssuerSpecVaultAuthAppRole(
            string path,

            string roleId,

            ClusterIssuerSpecVaultAuthAppRoleSecretRef secretRef)
        {
            Path = path;
            RoleId = roleId;
            SecretRef = secretRef;
        }
    }
}
