// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Ubiquitous.AutoDevOps.Crds.CertManager.Certmanager.V1Beta1.Outputs
{

    [OutputType]
    public sealed class ClusterIssuerSpecAcmeSolversDns01
    {
        /// <summary>
        /// Use the 'ACME DNS' (https://github.com/joohoi/acme-dns) API to manage DNS01 challenge records.
        /// </summary>
        public readonly ClusterIssuerSpecAcmeSolversDns01AcmeDNS AcmeDNS;
        /// <summary>
        /// Use the Akamai DNS zone management API to manage DNS01 challenge records.
        /// </summary>
        public readonly ClusterIssuerSpecAcmeSolversDns01Akamai Akamai;
        /// <summary>
        /// Use the Microsoft Azure DNS API to manage DNS01 challenge records.
        /// </summary>
        public readonly ClusterIssuerSpecAcmeSolversDns01AzureDNS AzureDNS;
        /// <summary>
        /// Use the Google Cloud DNS API to manage DNS01 challenge records.
        /// </summary>
        public readonly ClusterIssuerSpecAcmeSolversDns01CloudDNS CloudDNS;
        /// <summary>
        /// Use the Cloudflare API to manage DNS01 challenge records.
        /// </summary>
        public readonly ClusterIssuerSpecAcmeSolversDns01Cloudflare Cloudflare;
        /// <summary>
        /// CNAMEStrategy configures how the DNS01 provider should handle CNAME records when found in DNS zones.
        /// </summary>
        public readonly string CnameStrategy;
        /// <summary>
        /// Use the DigitalOcean DNS API to manage DNS01 challenge records.
        /// </summary>
        public readonly ClusterIssuerSpecAcmeSolversDns01Digitalocean Digitalocean;
        /// <summary>
        /// Use RFC2136 ("Dynamic Updates in the Domain Name System") (https://datatracker.ietf.org/doc/rfc2136/) to manage DNS01 challenge records.
        /// </summary>
        public readonly ClusterIssuerSpecAcmeSolversDns01Rfc2136 Rfc2136;
        /// <summary>
        /// Use the AWS Route53 API to manage DNS01 challenge records.
        /// </summary>
        public readonly ClusterIssuerSpecAcmeSolversDns01Route53 Route53;
        /// <summary>
        /// Configure an external webhook based DNS01 challenge solver to manage DNS01 challenge records.
        /// </summary>
        public readonly ClusterIssuerSpecAcmeSolversDns01Webhook Webhook;

        [OutputConstructor]
        private ClusterIssuerSpecAcmeSolversDns01(
            ClusterIssuerSpecAcmeSolversDns01AcmeDNS acmeDNS,

            ClusterIssuerSpecAcmeSolversDns01Akamai akamai,

            ClusterIssuerSpecAcmeSolversDns01AzureDNS azureDNS,

            ClusterIssuerSpecAcmeSolversDns01CloudDNS cloudDNS,

            ClusterIssuerSpecAcmeSolversDns01Cloudflare cloudflare,

            string cnameStrategy,

            ClusterIssuerSpecAcmeSolversDns01Digitalocean digitalocean,

            ClusterIssuerSpecAcmeSolversDns01Rfc2136 rfc2136,

            ClusterIssuerSpecAcmeSolversDns01Route53 route53,

            ClusterIssuerSpecAcmeSolversDns01Webhook webhook)
        {
            AcmeDNS = acmeDNS;
            Akamai = akamai;
            AzureDNS = azureDNS;
            CloudDNS = cloudDNS;
            Cloudflare = cloudflare;
            CnameStrategy = cnameStrategy;
            Digitalocean = digitalocean;
            Rfc2136 = rfc2136;
            Route53 = route53;
            Webhook = webhook;
        }
    }
}
