// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Ubiquitous.AutoDevOps.Crds.CertManager.Certmanager.V1Beta1.Outputs
{

    [OutputType]
    public sealed class IssuerSpecVenafiCloud
    {
        /// <summary>
        /// APITokenSecretRef is a secret key selector for the Venafi Cloud API token.
        /// </summary>
        public readonly IssuerSpecVenafiCloudApiTokenSecretRef ApiTokenSecretRef;
        /// <summary>
        /// URL is the base URL for Venafi Cloud. Defaults to "https://api.venafi.cloud/v1".
        /// </summary>
        public readonly string Url;

        [OutputConstructor]
        private IssuerSpecVenafiCloud(
            IssuerSpecVenafiCloudApiTokenSecretRef apiTokenSecretRef,

            string url)
        {
            ApiTokenSecretRef = apiTokenSecretRef;
            Url = url;
        }
    }
}
