// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

namespace Ubiquitous.AutoDevOps.Crds.Prometheus.Monitoring.V1.Inputs
{

    public class PodMonitorSpecPodMetricsEndpointsTargetPortArgs : Pulumi.ResourceArgs
    {
        public PodMonitorSpecPodMetricsEndpointsTargetPortArgs()
        {
        }
    }
}
