// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Ubiquitous.AutoDevOps.Crds.Prometheus.Monitoring.V1.Inputs
{

    /// <summary>
    /// BasicAuth allow an endpoint to authenticate over basic authentication. More info: https://prometheus.io/docs/operating/configuration/#endpoint
    /// </summary>
    public class PodMonitorSpecPodMetricsEndpointsBasicAuthArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The secret in the service monitor namespace that contains the password for authentication.
        /// </summary>
        [Input("password")]
        public Input<PodMonitorSpecPodMetricsEndpointsBasicAuthPasswordArgs>? Password { get; set; }

        /// <summary>
        /// The secret in the service monitor namespace that contains the username for authentication.
        /// </summary>
        [Input("username")]
        public Input<PodMonitorSpecPodMetricsEndpointsBasicAuthUsernameArgs>? Username { get; set; }

        public PodMonitorSpecPodMetricsEndpointsBasicAuthArgs()
        {
        }
    }
}
