// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Ubiquitous.AutoDevOps.Crds.Prometheus.Monitoring.V1.Inputs
{

    /// <summary>
    /// TLS configuration to use when scraping the endpoint.
    /// </summary>
    public class PodMonitorSpecPodMetricsEndpointsTlsConfigArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Struct containing the CA cert to use for the targets.
        /// </summary>
        [Input("ca")]
        public Input<PodMonitorSpecPodMetricsEndpointsTlsConfigCaArgs>? Ca { get; set; }

        /// <summary>
        /// Struct containing the client cert file for the targets.
        /// </summary>
        [Input("cert")]
        public Input<PodMonitorSpecPodMetricsEndpointsTlsConfigCertArgs>? Cert { get; set; }

        /// <summary>
        /// Disable target certificate validation.
        /// </summary>
        [Input("insecureSkipVerify")]
        public Input<bool>? InsecureSkipVerify { get; set; }

        /// <summary>
        /// Secret containing the client key file for the targets.
        /// </summary>
        [Input("keySecret")]
        public Input<PodMonitorSpecPodMetricsEndpointsTlsConfigKeySecretArgs>? KeySecret { get; set; }

        /// <summary>
        /// Used to verify the hostname for the targets.
        /// </summary>
        [Input("serverName")]
        public Input<string>? ServerName { get; set; }

        public PodMonitorSpecPodMetricsEndpointsTlsConfigArgs()
        {
        }
    }
}
