// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Ubiquitous.AutoDevOps.Crds.CertManager.Acme.V1Beta1.Outputs
{

    [OutputType]
    public sealed class ChallengeSpecSolverDns01AcmeDNS
    {
        /// <summary>
        /// A reference to a specific 'key' within a Secret resource. In some instances, `key` is a required field.
        /// </summary>
        public readonly ChallengeSpecSolverDns01AcmeDNSAccountSecretRef AccountSecretRef;
        public readonly string Host;

        [OutputConstructor]
        private ChallengeSpecSolverDns01AcmeDNS(
            ChallengeSpecSolverDns01AcmeDNSAccountSecretRef accountSecretRef,

            string host)
        {
            AccountSecretRef = accountSecretRef;
            Host = host;
        }
    }
}
