// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Ubiquitous.AutoDevOps.Crds.CertManager.Acme.V1Beta1.Outputs
{

    [OutputType]
    public sealed class ChallengeSpecSolverDns01Digitalocean
    {
        /// <summary>
        /// A reference to a specific 'key' within a Secret resource. In some instances, `key` is a required field.
        /// </summary>
        public readonly ChallengeSpecSolverDns01DigitaloceanTokenSecretRef TokenSecretRef;

        [OutputConstructor]
        private ChallengeSpecSolverDns01Digitalocean(ChallengeSpecSolverDns01DigitaloceanTokenSecretRef tokenSecretRef)
        {
            TokenSecretRef = tokenSecretRef;
        }
    }
}
