// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;
using Pulumi;

namespace Ubiquitous.AutoDevOps.Crds.CertManager.Acme.V1Beta1.Outputs
{

    [OutputType]
    public sealed class OrderStatus
    {
        /// <summary>
        /// Authorizations contains data returned from the ACME server on what authorizations must be completed in order to validate the DNS names specified on the Order.
        /// </summary>
        public readonly ImmutableArray<OrderStatusAuthorizations> Authorizations;
        /// <summary>
        /// Certificate is a copy of the PEM encoded certificate for this Order. This field will be populated after the order has been successfully finalized with the ACME server, and the order has transitioned to the 'valid' state.
        /// </summary>
        public readonly string Certificate;
        /// <summary>
        /// FailureTime stores the time that this order failed. This is used to influence garbage collection and back-off.
        /// </summary>
        public readonly string FailureTime;
        /// <summary>
        /// FinalizeURL of the Order. This is used to obtain certificates for this order once it has been completed.
        /// </summary>
        public readonly string FinalizeURL;
        /// <summary>
        /// Reason optionally provides more information about a why the order is in the current state.
        /// </summary>
        public readonly string Reason;
        /// <summary>
        /// State contains the current state of this Order resource. States 'success' and 'expired' are 'final'
        /// </summary>
        public readonly string State;
        /// <summary>
        /// URL of the Order. This will initially be empty when the resource is first created. The Order controller will populate this field when the Order is first processed. This field will be immutable after it is initially set.
        /// </summary>
        public readonly string Url;

        [OutputConstructor]
        private OrderStatus(
            ImmutableArray<OrderStatusAuthorizations> authorizations,

            string certificate,

            string failureTime,

            string finalizeURL,

            string reason,

            string state,

            string url)
        {
            Authorizations = authorizations;
            Certificate = certificate;
            FailureTime = failureTime;
            FinalizeURL = finalizeURL;
            Reason = reason;
            State = state;
            Url = url;
        }
    }
}
